In [40]:
import numpy as np
import random

In [41]:
#printing 1d array
a = np.array([1,2,3],dtype = "int16")
print(a)

[1 2 3]


In [42]:
#printing 2d array
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [43]:
#get dimension
a.ndim
b.ndim

2

In [44]:
# Get Shape
b.shape

(2, 3)

In [45]:
# Get Type
a.dtype

dtype('int16')

In [46]:
# Get Size
a.itemsize

2

In [47]:
#Get total size
a.size


3

#Access/Change specific elemtents

In [48]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])


In [49]:
#Get a specific element [r, c]
a[1,-6]


9

In [50]:
#Get specific row
a[0,:]


array([1, 2, 3, 4, 5, 6, 7])

In [51]:
#Get specific column
print(a)
a[:,2]


[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


array([ 3, 10])

In [52]:
#[startindex:endindex:stepsize]
a[0,1:6:2]

array([2, 4, 6])

In [53]:
#Changing stuff
a[1,6] = 90
print(a)

a[:,2] = [1,2]
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 90]]
[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 13 90]]


In [54]:
#3d example
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [55]:
#Get Specific element (work outside in)
b[:,0,:]


array([[1, 2],
       [5, 6]])

In [56]:
# replace 
b[1,1,0] = 9
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [9 8]]]


In [57]:
#All 0s matrix
# (dimention,m,x)
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [58]:
#all 1s
np.ones((4,2,2),dtype="int32")

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

In [59]:
#any other number
np.full((2,2),99,dtype="float32")

array([[99., 99.],
       [99., 99.]], dtype=float32)

In [60]:
#Any other number (full_like)
np.full(a.shape,4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [61]:
np.random.rand(4,2,2)

array([[[0.43208366, 0.6699509 ],
        [0.53323772, 0.94458966]],

       [[0.27883895, 0.21598661],
        [0.5523562 , 0.71100891]],

       [[0.57687321, 0.07356987],
        [0.43470586, 0.83571979]],

       [[0.36920238, 0.51619629],
        [0.64907835, 0.21601338]]])

In [62]:
np.random.random_sample(a.shape)

array([[0.1129497 , 0.93397204, 0.03837843, 0.08816341, 0.42198248,
        0.5577488 , 0.04636715],
       [0.24480104, 0.61659923, 0.28564177, 0.3230876 , 0.98825966,
        0.4217346 , 0.08482518]])

In [63]:
#random integers
np.random.randint(4,8,size=(3,3))

array([[6, 4, 5],
       [4, 4, 6],
       [7, 6, 5]])

In [64]:
#identity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [65]:
#repeat array
arr  =np.array([[[1,2,3]]])
np.repeat(arr,3,axis = 2)
#axis = 0 ->z, 1->y,2->x

array([[[1, 1, 1, 2, 2, 2, 3, 3, 3]]])

In [66]:
a = np.ones((5,5),dtype = "int32")
a[1:4,1:4] = 0 
a[2,2] = 9
a

array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 9, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]])

In [67]:
##copying
a = np.array([1,2,3])
b = a.copy()
b[0] = 100
print(a,b)

[1 2 3] [100   2   3]


In [68]:
a = np.array([1,2,3,4])
print(a+2)
print(a-2)
print(a*2)

[3 4 5 6]
[-1  0  1  2]
[2 4 6 8]


In [69]:
b = np.array([1,0,1,0])
a+b

array([2, 2, 4, 4])

In [70]:
x = np.array([1,2,3,4])

In [71]:
#take the sin and cos
np.sin(x)
np.cos(x)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

###Linear Algebra



In [81]:
x = np.ones((2,3))
print(x)

b = np.full((3,2),4)
print(b)

np.matmul(x,b) #Matrix multiply

[[1. 1. 1.]
 [1. 1. 1.]]
[[4 4]
 [4 4]
 [4 4]]


array([[12., 12.],
       [12., 12.]])

In [84]:
c = np.ones((3,3))
np.linalg.det(c)

0.0

####Stats

In [88]:
stats = np.array([[1,2,3],[4,5,6]])
stats
np.min(stats)
np.max(stats,axis = 1)

array([3, 6])

####Reorganize

In [91]:
a1 = np.array([[1,2,3,4],[5,6,7,8]])
print(a1)

a2 = a1.reshape(4,2)
print(a2)
#Has to have same number of values

[[1 2 3 4]
 [5 6 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [99]:
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])
np.vstack([v1,v2])
np.vstack([v1,v2,v1,v1])
#vertical stacking


array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [1, 2, 3, 4]])

In [100]:
h1 = np.ones((2,4))
h2 = np.zeros((2,2))

np.hstack((h1,h2))
#horizontal stacking

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

####Other values


In [106]:
extdata = np.genfromtxt('data.txt',delimiter = ',',dtype="int32")
print(extdata)
#default is float
newextdata = extdata.astype("float32")# type conversion
print(newextdata)

[[  1  13  21  11 196  75   4   3  34   6   7   8   0   1   2   3   4   5]
 [  3  42  12  33 766  75   4  55   6   4   3   4   5   6   7   0  11  12]
 [  1  22  33  11 999  11   2   1  78   0   1   2   9   8   7   1  76  88]]
[[  1.  13.  21.  11. 196.  75.   4.   3.  34.   6.   7.   8.   0.   1.
    2.   3.   4.   5.]
 [  3.  42.  12.  33. 766.  75.   4.  55.   6.   4.   3.   4.   5.   6.
    7.   0.  11.  12.]
 [  1.  22.  33.  11. 999.  11.   2.   1.  78.   0.   1.   2.   9.   8.
    7.   1.  76.  88.]]


####Advaned Indexing

In [108]:
extdata>50

array([[False, False, False, False,  True,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [110]:
extdata[extdata>50]

array([196,  75, 766,  75,  55, 999,  78,  76,  88])

In [113]:
#indexing with list
down = np.array([1,2,3,4,5,6,7,8,9])
down[[1,2,8]]

array([2, 3, 9])

In [114]:
print(extdata)

[[  1  13  21  11 196  75   4   3  34   6   7   8   0   1   2   3   4   5]
 [  3  42  12  33 766  75   4  55   6   4   3   4   5   6   7   0  11  12]
 [  1  22  33  11 999  11   2   1  78   0   1   2   9   8   7   1  76  88]]


In [117]:
np.any(extdata>50, axis = 1)
#if any values are greater than 50 on the given axis(or)
np.all(extdata>50, axis = 0)
#if all values are greater than 50 on the given axis(and)


array([False, False, False, False,  True, False, False, False, False,
       False, False, False, False, False, False, False, False, False])

In [121]:
print((extdata>50) & (extdata<100))

[[False False False False False False False False False False False False
  False False False False False False]
 [False False False False False False False False False False False False
  False False False False False False]
 [False False False False False False False False False False False False
  False False False False False False]]


In [122]:
#operations on arrays(stats)
w = np.random.normal(5, 0.5, 10)#(loc,scale,size) loc - mean, scale - median, size - of matrix
print(np.min(w))
print(np.max(w))
print(np.mean(w))
print(np.std(w))
print(np.median(w))


3.810916663658186
5.737331700298972
5.106258427115593
0.5697265580871695


In [123]:
## Linear algebra
### Dot product: product of two arrays
f = np.array([1,2])
g = np.array([4,5])
### 1*4+2*5
np.dot(f, g)

14